### ISSUE TITLE
Encode from base64?

### ISSUE THREAD

**Issue by acterhd** [Intervox/node-webp#10]
Hello. Can I encode WebP from base64 coded image?

**Comment by lbeschastny** [comment]
@acterhd sure, just convert it to `Buffer` first

```
new Buffer(b64string, 'base64')
```

See: [How to do Base64 encoding in node.js?](http://stackoverflow.com/a/6182519/1202461)

**Comment by acterhd** [comment]
I think, I can close, because I found anwser.
