### ISSUE TITLE
Low level API 

### ISSUE THREAD

**Issue by acterhd** [Intervox/node-webp#11]
Please, make low-level version of node-webp. Use same libraries, but through "include" and "lib". Write io.js addon, that builds by GYP. Through command line are not very fast.

**Comment by lbeschastny** [comment]
Am I right that you're asking me to make a native node.js binding for `libwebp` library?

**Comment by acterhd** [comment]
Yes, also I want webpmux support. I can help you write command line wrapper, but for libwebp need your help for me.

**Comment by acterhd** [comment]
Да, мне хотелось бы native библиотека. И еще mux.

**Comment by lbeschastny** [comment]
I would be great to have a native bindings for `libwebp`, but unfortunately I'm not going to do it. The main reason is that it'll require a lot of additional work from my side and I'm short of time right now.

And anyway, the module was designed as a lightweight wrapper for webp cli, so to create native `libwebp` binding we'll have to start a separate project.

--

Иметь нативные биндинги для webp было бы очень здорово, но:

1. Я не возьмусь за этот проект, т.к. у меня сейчас очень мало времени, да и опыта в разработке нативных модулей у меня маловато.
2. `node-webp` был спроектирован именно как легковесный врапер над cli. Чтобы сделать нативный модуль придется начать с чистого листа, причем лучше всего в отдельном проекте.

Я согласен, что нативный модуль будет работать гораздо быстрее. Но я не считаю, что прирост скорости за счет разработки нативного модуля окупит потраченное время.

Что касается `mux`, то добавить для него поддержку должо быть не сложно. Скорее всего, будет достаточно грамотно заполнить [methods.json]. В любом случае, я готов помочь с интеграцией `mux`. В принципе, я могу попробовать сделать это сам, но поскольку я сейчас довольно загружен, у меня на это может уйти не один месяц.

  [methods.json]: https://github.com/Intervox/node-webp/blob/master/methods.json

**Comment by lbeschastny** [comment]
Что касается нативных биндингов, то я с удовольствием прикручу их к `node-webp`, если кто-нибудь их разработает и выложит в `npm`. Сам я не готов сейчас этим заниматься.

**Comment by acterhd** [comment]
Просто у меня особый случай - мне надо конвертировать APNG в WebP на лету.

**Comment by lbeschastny** [comment]
Да, тут нативный модуль бы пригодился...
