### ISSUE TITLE
Cannot decode webp

### ISSUE THREAD

**Issue by tom-james-watson** [Intervox/node-webp#12]
Hi, I'm trying to decode a webp to a png, but having a bit of trouble.

Here's my basic sanity-test example (using this file https://www.gstatic.com/webp/gallery3/1_webp_ll.webp):

```
let decoder = cwebp.DWebp('1_webp_ll.webp');
decoder.write('output.png', function(err) {
    console.log(err || 'decoded successfully');
});
```

output is:
```
> { [Error: spawn dwebp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn dwebp',
  path: 'dwebp',
  spawnargs: [ '-o', 'output.png', '--', '1_webp_ll.webp' ] }
```

Any ideas?

Many thanks.

**Comment by lbeschastny** [comment]
`ENOENT` means “No such directory entry”.

So, you either don't have `webp` binary in your path, or don't have `1_webp_ll.webp` file in your current working directory.

**Comment by tom-james-watson** [comment]
Ah I didn't realise you needed webp in path.
