### ISSUE TITLE
Support graceful shutdown

### ISSUE THREAD

**Issue by rnavarroz** [Intervox/node-webp#30]
Could we set the options for the spawn function used on the wrapper.js  (Wrapper.prototype._spawn)?
I want to handle a graceful shutdown when the application is running the cwebp, it can finish adequately, this is possible if we can set on the options of the spawn with detached to true

https://nodejs.org/api/child_process.html#child_process_options_detached

**Comment by lbeschastny** [comment]
So, if I understand you correctly, you want to wait for all ongoing webp child processes to finish whatever they are doing before terminating the main process, right?

I'm not sure that passing `detached: true` option to `child_process.spawn` is the right way to achieve this. Instead, you should probably intercept relevant signals and close all resources blocking node.js from shutting down (i.e. http servers, database connection, etc.).

Or do you want webp child processes to keep running when the main process is shut down?

Anyway, If you could describe your particular use-case, I may be able to help you find a good solution.

Though, it shouldn't be hard to accept custom options for `child_process.spawn` call. The only question if how the API should look. I guess `.write()`, `.toBuffer()` and `.stream()` methods could accept one additional optional argument. Or we could add some new method to set spawn options, i.e. `.spawnOptions()`. But I don't think setting `detached` option to `true` will solve your problem.

**Comment by rnavarroz** [comment]
Hi, yes it's right, I want to let the cwebp child process to finish before to close the process. Currently when the application is shutdown  the child process with cwebp is forcing to be closed as well and letting the process incomplete. 

The detached option to true has been a solution for other commands that I run like with gifsicle and execa package. That's why my request to add the option to include more args to spawn to be customizable.

**Comment by lbeschastny** [comment]
The best way to implement graceful shutdown is to handle termination signals either manually

```js
const onExit = () => {
	httpServer.close();
	dbConnection.close();
	someOtherResourse.close();
	console.log('Exit signal received, the process will shut down soon');
}

process.once('SIGINT', onExit);
process.once('SIGTERM', onExit);
```

or using some npm package like [exit-hook](https://www.npmjs.com/package/exit-hook) or [signal-exit](https://www.npmjs.com/package/signal-exit)

```js
import {asyncExitHook} from 'exit-hook';

asyncExitHook(async () => {
	await httpServer[Symbol.asyncDispose]();
	await dbConnection.close();
}, {
	minimumWait: 5000 // force termination after 5 seconds
});
```

**Comment by rnavarroz** [comment]
Thanks @lbeschastny, I already have the graceful shutdown implementation but I have seen that the child process for cwebp was interrupted, that's why came this request.  However I have tried to reproduce the issue again and I am not able to see it anymore.

Although still it would be a nice feature to have a way to add more options for a "spawn" but given I don't have a strong case to request it. We can close this issue.

**Comment by lbeschastny** [comment]
I could take a look. But we have to find some good way to pass swan options without breaking existing functionality
