### ISSUE TITLE
encoder.write doesn't work when the source is buffer

### ISSUE THREAD

**Issue by hh54188** [Intervox/node-webp#5]
Here is my code:
```
fs.readFile('./sample.jpg', function (err, data) {
	var encoder = new CWebp(data);
	encoder.write('./image.webp', function (err) {
		console.log(err || 'encoded successfully');
	});
});
```
I read an image file from disk and using the binaries data as buffer to  convert.
But I can't output the webp file. The cmd told me:

```
{ [Error: ENOENT, open 'c:\tmp\node-webp-95yx5bup4x.tmp']
  errno: 34,
  code: 'ENOENT',
  path: 'c:\\tmp\\node-webp-95yx5bup4x.tmp' }
```

**Comment by lbeschastny** [comment]
Works for me.

Please, provide the following information:

 * node.js version `node --version`
 * cwebp version `cwebp -version`
 * `node-webp` version you're using (is it latest 1.0.3 version?)

But probably it's a windows-specific issue.

In this case, I won't be able to reproduce your problem until I'll adopt a windows-based CI tool.

**Comment by lbeschastny** [comment]
The problem with buffers is that [cwebp] have no support for streaming yet, so there is no way to send data to [cwebp] without creating a temporary file first.

There is an [open issue][1] on the [webp issue tracker][2] for it. I opened it on March 2014, but webp team haven't fixed it yet.

As for you problem, it looks like something got wrong with temporary file creation, though I have no idea what.

  [cwebp]: https://developers.google.com/speed/webp/docs/cwebp
  [1]: http://code.google.com/p/webp/issues/detail?id=191
  [2]: http://code.google.com/p/webp/issues/list

**Comment by lbeschastny** [comment]
@hh54188 I can't reproduce your problem on ubuntu, so there is nothing I can do right now.

Right now I don't have time to look deeper into your problem, and I won't have any until May.

**Comment by hh54188** [comment]
- OS: Windows 8.1 64bits. 
- Node version: v0.10.32
- cwebp: 0.4.2-windows-x86

And I think the `node-webp` is the lasest.
Actually I have solve this problem by adding a named `tmp` in the `c:/`

**Comment by lbeschastny** [comment]
`node-webp` resolves system tmp directory from the environment. Look like you had misconfigured `TMPDIR` variable.

**Comment by lbeschastny** [comment]
@hh54188 I improved tmp directory lookup algorithm.

Please, check latest `1.0.5` release. I believe it should resolve your problem.
